/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, drupalSettings) {
    $(document).ready(function () {
      $.ajax({
        type: 'GET',
        cache: false,
        url: 'recordVisit',
        success: function(data) {
          // console.log(data);
        },
        error: function() {
        }
      });
    });
  })(jQuery, Drupal, drupalSettings);